server:
  port: 8999

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: myTest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.30.172:3306/testdb?serverTimezone=UTC
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.myl.test.springbootstudy.model
  mapper-locations:
    - mapper/*
